# MarriageMaster BungeeCord Config File.

# Language Settings
Language:
  # Defines the used language and the corresponding file used. The corresponding language file will be placed next to the config.yml named: <Language>.yml
  Language: en
  # Options:
  #     Overwrite (deletes all changes from the file and extracts a new language file)
  #     Upgrade (extracts a new language file and copy's all settings from the old language file)
  #     Update (adds the default (english) text values for all missing values, just some basic formatting)
  UpdateMode: Upgrade

InfoOnPartnerJoinLeave:
  Enable: true
  # Delay for online partners info on join. In seconds
  JoinDelay: 0

Marriage:
  AllowMultiplePartners: false
  Surnames:
    Enable: false
    Force: false

Chat:
  # If turned off the marry chat function will be handled by the bukkit server (Private chat will only work if both players are on the same server)
  Global: true

Home:
  # If turned off the marry home function will be handled by the bukkit server (homes will only work if the player is on the same server as his home)
  Global: true
  # Disable delay on the bukkit server!
  Delayed: false
  # List of Servers where it's not possible to teleport from
  BlockedFrom: []
  # List of Servers where it's not possible to teleport to
  BlockedTo: []

Teleport:
  # If turned off the marry tp function will be handled by the bukkit server (tp will only work if both players are on the same server)
  Global: true
  # Disable delay on the bukkit server!
  Delayed: false
  # List of Servers where it's not possible to teleport from
  BlockedFrom: []
  # List of Servers where it's not possible to teleport to
  BlockedTo: []

Database:
  # MySQL = data stored in MySQL database (see selection below)
  Type: MySQL
  UseUUIDSeparators: false
  # Options: auto, online, offline | auto will decide based on the server online mode option.
  # If you are using BungeeCord, set it to whatever you use on your BungeeCord server!!!
  UUID_Type: auto
  # MySQL Settings must match the settings in your bukkit plugin config.
  SQL:
    Host: localhost
    Database: minecraft
    User: minecraft
    Password: minecraft
    MaxConnections: 2
    # Allows to set the connection properties.
    # Properties: ["useSSL=false"]
    Properties: []
    Tables:
      User: marry_players
      Partner: marry_partners
      Home: marry_home
      Priests: marry_priests
  # Settings controlling the cache behavior of the plugin. You may can optimize it a little bit depending on your player count, ram or cpu bottlenecks.
  Cache:
    UnCache:
      # The strategie used to uncache offline players. Options
      #     interval (offline players get uncached every x seconds)
      #     intervalChecked (like interval, but also ensures that the player is already offline for at lest the interval time, add's a cpu overhead)
      #     ondisconnect (player instantly gets uncached as soon as he disconnects from the server, may adds overhead if other plugins try to access the player data when they go offline, also it may be problematic for players with unstable connections)
      #     ondisconnectdelayed (player gets uncached x seconds after he went offline, adds overhead on disconnect, you shouldn't use this with a lot of players joining and leaving.)
      Strategie: interval
      # Used for the interval based uncaching algorithms. Also used as delay for ondisconnectdelayed. Value in seconds. Default: 600 = 10 minutes
      Interval: 600
      Delay: 600

Misc:
  # Only Downloads the update to the "updates" folder. You will have to move it manually or let you system move it in the startup script.
  # If turned off you still can use /marry update to download the update
  AutoUpdate: true

# Config File Version. Don't touch it!
Version: 100